name: pep8

on: [push]

jobs:
  flake8:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache packages
        uses: actions/cache@v2
        env:
          cache-name: python-${{ matrix.python-version }}
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-flake8
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          # Python 構文エラーまたは未定義の名前がある場合はビルドを停止する
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zeroはすべてのエラーを警告として扱う。 GitHubのエディタの幅は127文字
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics